package cobra

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
)

type sshPaths struct {
	prefix  string
	config  string
	runtime string
	pid     string
	log     string
	wrapper string
}

func mobdeskSSHPaths() sshPaths {
	prefix := os.Getenv("PREFIX")
	if prefix == "" {
		prefix = "/data/data/com.termux/files/usr"
	}
	home := os.Getenv("HOME")
	if home == "" {
		home = os.Getenv("USERPROFILE")
	}
	if home == "" {
		home = "."
	}

	runtime := filepath.Join(home, ".local", "share", "mobdesk", "ssh")
	return sshPaths{
		prefix:  prefix,
		config:  filepath.Join(home, ".config", "mobdesk", "ssh", "sshd_config"),
		runtime: runtime,
		pid:     filepath.Join(runtime, "sshd.pid"),
		log:     filepath.Join(runtime, "sshd.log"),
		wrapper: filepath.Join(runtime, "mobdesk-ssh-shell"),
	}
}

func renderSSHConfig(paths sshPaths) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Generated by Mobdesk. Do not edit.\nPort %d\n", sshPort)
	fmt.Fprintf(&builder, "ListenAddress 0.0.0.0\nPidFile %s\n", paths.pid)
	fmt.Fprintf(&builder, "ForceCommand %s\n", paths.wrapper)
	builder.WriteString("PasswordAuthentication yes\n")
	builder.WriteString("KbdInteractiveAuthentication yes\n")
	builder.WriteString("PermitEmptyPasswords no\n")
	builder.WriteString("StrictModes no\n")

	for _, keyType := range []string{"rsa", "ecdsa", "ed25519"} {
		keyPath := filepath.Join(paths.prefix, "etc", "ssh", "ssh_host_"+keyType+"_key")
		if _, err := os.Stat(keyPath); err == nil {
			fmt.Fprintf(&builder, "HostKey %s\n", keyPath)
		}
	}

	sftp := filepath.Join(paths.prefix, "libexec", "sftp-server")
	if _, err := os.Stat(sftp); err == nil {
		fmt.Fprintf(&builder, "Subsystem sftp %s\n", sftp)
	}
	return builder.String()
}

func writeSSHWrapper(paths sshPaths) error {
	if err := os.MkdirAll(paths.runtime, 0o700); err != nil {
		return fmt.Errorf("criar runtime SSH do Mobdesk: %w", err)
	}
	shell := filepath.Join(paths.prefix, "bin", "sh")
	proot := filepath.Join(paths.prefix, "bin", "proot-distro")
	wrapper := fmt.Sprintf("#!%s\nexec %s login ubuntu -- bash -l\n", shell, proot)
	if err := os.WriteFile(paths.wrapper, []byte(wrapper), 0o700); err != nil {
		return fmt.Errorf("criar shell SSH do Ubuntu: %w", err)
	}
	return nil
}

func writeSSHConfig(paths sshPaths) error {
	if err := os.MkdirAll(filepath.Dir(paths.config), 0o700); err != nil {
		return fmt.Errorf("criar diretório da configuração SSH: %w", err)
	}
	if err := os.MkdirAll(paths.runtime, 0o700); err != nil {
		return fmt.Errorf("criar runtime SSH do Mobdesk: %w", err)
	}

	temporary, err := os.CreateTemp(filepath.Dir(paths.config), "sshd_config.*.tmp")
	if err != nil {
		return fmt.Errorf("criar configuração SSH temporária: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return fmt.Errorf("proteger configuração SSH temporária: %w", err)
	}
	if _, err := temporary.WriteString(renderSSHConfig(paths)); err != nil {
		temporary.Close()
		return fmt.Errorf("escrever configuração SSH temporária: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("fechar configuração SSH temporária: %w", err)
	}
	if err := validateSSHConfig(temporaryPath); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, paths.config); err != nil {
		return fmt.Errorf("instalar configuração SSH do Mobdesk: %w", err)
	}
	return nil
}

func ensureMobdeskSSH() error {
	paths := mobdeskSSHPaths()
	if err := writeSSHWrapper(paths); err != nil {
		return err
	}
	return writeSSHConfig(paths)
}

func processCommandLine(pid int) (string, error) {
	bytes, err := os.ReadFile(fmt.Sprintf("/proc/%d/cmdline", pid))
	if err != nil {
		return "", err
	}
	return strings.ReplaceAll(string(bytes), "\x00", " "), nil
}

func processIsMobdeskSSH(pid int, configPath string) bool {
	commandLine, err := processCommandLine(pid)
	if err != nil || !strings.Contains(commandLine, configPath) {
		return false
	}
	executable, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid))
	if err != nil {
		return false
	}
	return filepath.Base(executable) == "sshd"
}

type sshLock struct {
	file *os.File
}

func acquireSSHLock() (*sshLock, error) {
	paths := mobdeskSSHPaths()
	if err := os.MkdirAll(paths.runtime, 0o700); err != nil {
		return nil, fmt.Errorf("criar lock do SSH: %w", err)
	}
	file, err := os.OpenFile(filepath.Join(paths.runtime, "sshd.lock"), os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("abrir lock do SSH: %w", err)
	}
	if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		file.Close()
		return nil, fmt.Errorf("outro comando do Mobdesk já está controlando o SSH: %w", err)
	}
	return &sshLock{file: file}, nil
}

func (lock *sshLock) release() {
	if lock == nil || lock.file == nil {
		return
	}
	_ = syscall.Flock(int(lock.file.Fd()), syscall.LOCK_UN)
	_ = lock.file.Close()
}
