package workstation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ericklucioh/mobdesk/internal/executil"
	"github.com/ericklucioh/mobdesk/internal/paths"
)

// EnsureSSHConfigured writes and validates the dedicated sshd configuration.
// Setup uses this entry point until its own orchestration moves into Service.
func EnsureSSHConfigured(p paths.Paths) error {
	if err := writeSSHWrapper(p); err != nil {
		return err
	}
	return writeSSHConfig(p)
}

func renderSSHConfig(p paths.Paths) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Generated by Mobdesk. Do not edit.\nPort %d\n", SSHPort)
	fmt.Fprintf(&builder, "ListenAddress 0.0.0.0\nPidFile %s\n", p.SSHPID())
	fmt.Fprintf(&builder, "ForceCommand %s\n", p.SSHWrapper())
	builder.WriteString("PasswordAuthentication yes\nKbdInteractiveAuthentication yes\nPermitEmptyPasswords no\nStrictModes no\n")
	for _, keyType := range []string{"rsa", "ecdsa", "ed25519"} {
		keyPath := filepath.Join(p.Prefix, "etc", "ssh", "ssh_host_"+keyType+"_key")
		if _, err := os.Stat(keyPath); err == nil {
			fmt.Fprintf(&builder, "HostKey %s\n", keyPath)
		}
	}
	sftp := filepath.Join(p.Prefix, "libexec", "sftp-server")
	if _, err := os.Stat(sftp); err == nil {
		fmt.Fprintf(&builder, "Subsystem sftp %s\n", sftp)
	}
	return builder.String()
}

func writeSSHWrapper(p paths.Paths) error {
	if err := os.MkdirAll(p.SSHRuntimeDir(), 0o700); err != nil {
		return fmt.Errorf("criar runtime SSH do Mobdesk: %w", err)
	}
	wrapper := fmt.Sprintf("#!%s\nexec %s login ubuntu -- bash --rcfile %s -i\n", filepath.Join(p.Prefix, "bin", "sh"), filepath.Join(p.Prefix, "bin", "proot-distro"), p.UbuntuShellConfig())
	if err := os.WriteFile(p.SSHWrapper(), []byte(wrapper), 0o700); err != nil {
		return fmt.Errorf("criar shell SSH do Ubuntu: %w", err)
	}
	return nil
}

func writeSSHConfig(p paths.Paths) error {
	if err := os.MkdirAll(filepath.Dir(p.SSHConfig()), 0o700); err != nil {
		return fmt.Errorf("criar diretório da configuração SSH: %w", err)
	}
	if err := os.MkdirAll(p.SSHRuntimeDir(), 0o700); err != nil {
		return fmt.Errorf("criar runtime SSH do Mobdesk: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(p.SSHConfig()), "sshd_config.*.tmp")
	if err != nil {
		return fmt.Errorf("criar configuração SSH temporária: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("proteger configuração SSH temporária: %w", err)
	}
	if _, err := temporary.WriteString(renderSSHConfig(p)); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("escrever configuração SSH temporária: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("fechar configuração SSH temporária: %w", err)
	}
	command, err := executil.Command("sshd", "-t", "-f", temporaryPath)
	if err != nil {
		return fmt.Errorf("resolver sshd: %w", err)
	}
	command.Stdout, command.Stderr = os.Stdout, os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Errorf("configuração do sshd inválida: %w", err)
	}
	if err := os.Rename(temporaryPath, p.SSHConfig()); err != nil {
		return fmt.Errorf("instalar configuração SSH do Mobdesk: %w", err)
	}
	return nil
}
